a=input("Enter the first two characters of present day").upper()

if a=="SU":
    b="Have a nice Sunday"
elif a=="MO":
    b="Have a nice Monday"
elif a=="TU":
    b="Have a nice Tuseday"
elif a=="WE":
    b="Have a nice Wednesday"
elif a=="TH":
    b="Have a nice Thursday"
elif a=="FR":
    b="Have a nice Friday"
elif a=="SA":
    b="Have a nice Saturday"
else:
    b="Wrong input"
print(b)
